name: Staging Build

on:
  push:
    branches:
      - staging # Triggers on any push or merge to the staging branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Creates the sensitive files from Repository Secrets
      - name: Create Config Files
        run: |
          mkdir -p android/app/src/staging/
          mkdir -p assets/config/
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/src/staging/google-services.json
          echo '${{ secrets.STAGING_CONFIG_JSON }}' > assets/config/config_staging.json

      - name: Install Dependencies
        run: flutter pub get
      
      # Build the specific flavor using the config file
      - name: Build Staging APK
        run: |
          flutter build apk --release --flavor staging \
          --dart-define-from-file=assets/config/config_staging.json

      # Makes the APK downloadable from the "Actions" tab
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: staging-apk
          path: build/app/outputs/flutter-apk/app-staging-release.apk
          retention-days: 90
